optimized format for the platform.in

diff --git a/etc/platform/bin/platform.in b/etc/platform/bin/platform.in
--- a/etc/platform/bin/platform.in
+++ b/etc/platform/bin/platform.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-if [ -n "${__PLATFORM_BIN_PLATFORM_IN__}" ]; then
+if [[ -n "${__PLATFORM_BIN_PLATFORM_IN__}" ]]; then
 	return
 else
 	__PLATFORM_BIN_PLATFORM_IN__="$0"
@@ -9,4 +9,135 @@ fi
 readonly FILE_REGISTER=/data/.register.json
 readonly FILE_CANCELLATION=/data/.cancellation.json
 readonly BACKUP_LOG=/mnt/flash/rootfs_data/backup/log/
+readonly CERTIFICATE=/etc/platform/conf/server.cer
+readonly USER_PASSWD=autelanauteviewlms:autelanauteviewlms20140925
 
+reg_check(){
+
+	local curl_ok=0
+	local curl_couldnt_connect=7 
+	local curl_couldnt_resolve_host=6  
+	local reconnection_interval=5  
+	local cookie_file="$1"
+	local url="$2"
+	local result_file="$3"  
+	local response_file="$4"  
+
+	while true
+	do
+		curl  -k  -cert "${CERTIFICATE}"  -u "${USER_PASSWD}"  -H "Content-type: application/json"  -X POST  -d @"${FILE_REGISTER}" -s  -c "${cookie_file}"  "${url}" > "${result_file}"
+		response=$?
+		echo response="${response}" > "${response_file}"
+		#		if [ $response -eq ${curl_couldnt_connect} ] || [ $response -eq ${curl_couldnt_resolve_host} ]; then
+		if [[ "${response}" != "${curl_ok}" ]]; then
+			sleep "${reconnection_interval}"
+		else
+			break
+		fi
+	done
+}
+
+reg_print_result(){
+
+	local result_file=$1
+
+	out=$(cat ${result_file} |jq '.code')
+	case $out in
+		0) 
+			echo "register success!"
+			;;
+		-1)	
+			echo "user/password error!"
+			;;
+		*) 
+			echo "register fail!"
+			;;
+	esac
+}
+
+register_operation() {
+
+	local page=lteRegister.do
+	local cookie_file=/tmp/registerCookie.txt
+	local result_file=/tmp/registerResult.txt
+	local response_file=/tmp/registerResponse.txt
+	local url_path=$1
+	local url_default=$2
+
+	if [[ -f "${result_file}" ]]; then
+		rm ${result_file}
+	fi
+
+	while [[ ! -f "${FILE_REGISTER}" ]]; do
+		sleep 5
+	done
+
+	if [[ -f "${FILE_REGISTER}" ]]; then
+		if [[ -s "${url_path}" ]]; then
+			url_path=$(cat ${url_path} |jq -j '.url')
+			url="${url_path}""${page}"
+		else
+			url="${url_default}""${page}"
+		fi
+		reg_check  "${cookie_file}" "${url}" "${result_file}"  "${response_file}"
+		rm -f "${response_file}"
+	
+		reg_print_result "${result_file}"
+	#	if [ -f $result_file ];then
+	#		rm $result_file
+	#	fi
+	else
+		echo ${FILE_REGISTER}" is not exist!"
+	fi
+}
+
+command_operation(){
+
+	local page=lteCommand.do
+	local cookie_file=/tmp/commandCookie.txt
+	local result_file=/tmp/commandResult.txt
+	local command_file=/tmp/command.txt
+	local command_file_re=/tmp/command_record.log
+	local url_path=$1
+	local url_default=$2
+	
+	if [[ -f "${FILE_REGISTER}" ]];then
+		if [[ -s "${url_path}" ]];then
+			url_path=`cat ${url_path} |jq -j '.url'`
+			url="${url_path}""${page}"
+		else
+			url="${url_default}""${page}"
+		fi
+		echo url="${url}"
+
+		macKey='{"mac":'
+		macValue=`cat ${FILE_REGISTER} |jq '.mac'`
+		endChar='}'
+		mac="${macKey}""${macValue}""${endChar}"
+		echo mac="${mac}"
+
+		curl  -k  -cert "${CERTIFICATE}"  -u "${USER_PASSWD}"  -H "Content-type: application/json"  -X POST  -d "${mac}"  -s  -c "${cookie_file}"  "${url}" > "${result_file}"
+
+		out=$(cat ${result_file} |jq -j '.cmd')
+		if [[ -f "${result_file}" ]]; then
+	                rm "${result_file}"
+	        fi
+		echo out="${out}"
+		result=$(echo "${out}" |base64 -d)
+		echo "${result}" |tr ";" "\n" > "${command_file}" 
+		cat "${command_file}" | while read myCommand
+		do
+	 		echo "Command:""${myCommand}"
+	 		echo "Get the Command :""${myCommand}"";time is :"`date`>> "${command_file_re}"
+			logger "platform" "command:$myCommand"
+
+			eval "${myCommand}"
+		done
+		if [[ -f "${command_file}" ]];then
+			rm "${command_file}"
+		fi
+	else
+		logger "platform" "$FILE_REGISTER is not exist!"
+	fi
+
+}
diff --git a/usr/sbin/userauth b/usr/sbin/userauth
--- a/usr/sbin/userauth
+++ b/usr/sbin/userauth
@@ -2,41 +2,152 @@
 
 . /etc/utils/utils.in
 
-mac="$1"
-group="$2"                          
-echo $group
-filepath="/tmp/config/group$group"
+get_group() {
+	local flow=$1	
+	local rate=$2	
+	local i=0
 
-if [ -f "$filepath" ]; then 
+	while [ -f "/etc/um/group${i}" ]
+	do
+	    local tmpflow=`awk '/wan_flow_all/{print $2}'  /etc/um/group${i}`
+	    local tmprate=`awk '/wan_rate_down/{print $2}'  /etc/um/group${i}`
+	    if ((flow>=tmpflow*1000 && rate==tmprate)); then
+	   	echo "$((i+1))" 
+	   	return  
+	    fi
+       	    ((i++))
+	done
+	echo "0"
+	return
+}
+do_umc_command() {
+	local mac=$1
+	local group=$2
+	local filepath=/etc/um/group"${group}" 
+	
+	if [ ! -f ${filepath} ]; then
+		return 1
+	fi
 
-onlineValue=`awk '/online/{print $2}'  $filepath`
-flowMax=`awk '/flow/{print $2}'  $filepath`
-rateMax=`awk '/rate/{print $2}'  $filepath`
-rateAvg=$rateMax
-echo "onlineValue=$onlineValue, $flowMax, $rateAvg"
+	local lan_online=`awk '/lan_online/{print $2}'  $filepath`
+	local wan_online=`awk '/wan_online/{print $2}'  $filepath`
 
-main() {
-        local josn                                
-                                                   
-       #json=$(json_create wan/online/max $onlineValue wan/flow/up/max $flowMax wan/flow/down/max $flowMax wan/flow/all/max $flowMax wan/rate/up/max $rateMax wan/rate/up/avg $rateAvg wan/rate/down/max $rateMax wan/rate/down/avg $rateAvg wan/rate/all/max $rateMax wan/rate/all/avg $rateAvg) 
-       json=$(json_create \
-       wan/online/max $onlineValue \
-       wan/flow/up/max $flowMax \
-       wan/flow/down/max $flowMax \
-       wan/flow/all/max $flowMax \
-       wan/rate/up/max $rateMax \
-       wan/rate/up/avg $rateAvg \
-       wan/rate/down/max $rateMax \
-       wan/rate/down/avg $rateAvg \
-       wan/rate/all/max $rateMax \
-       wan/rate/all/avg $rateAvg) 
-        
-        json=$(echo ${json} | jq -j -c .)                              
-        echo "umc auth $mac $group $json"    
-        umc auth $mac $group "$json"        
-}                                          
-                                           
-main "$@"   
-else
-    echo "Error:couldn't find $filepath"
-fi
+	local lan_flow_up=`awk '/lan_flow_up/{print $2}'  $filepath`
+	local lan_flow_down=`awk '/lan_flow_down/{print $2}'  $filepath`
+	local lan_flow_all=`awk '/lan_flow_all/{print $2}'  $filepath`
+	local wan_flow_up=`awk '/wan_flow_up/{print $2}'  $filepath`
+	local wan_flow_down=`awk '/wan_flow_down/{print $2}'  $filepath`
+	local wan_flow_all=`awk '/wan_flow_all/{print $2}'  $filepath`
+
+	local lan_rate_down=`awk '/lan_rate_down/{print $2}'  $filepath`
+	local lan_rate_up=`awk '/lan_rate_up/{print $2}'  $filepath`
+	local wan_rate_down=`awk '/wan_rate_down/{print $2}'  $filepath`
+	local wan_rate_up=`awk '/wan_rate_up/{print $2}'  $filepath`	
+	
+	local lan_idle=`awk '/lan_idle/{print $2}' $filepath`
+	local wan_idle=`awk '/wan_idle/{print $2}' $filepath`
+	
+	expr ${lan_online} +  ${wan_online} + ${lan_flow_up} + ${lan_flow_down} + ${lan_flow_all} \
+	     + ${wan_flow_up} + ${wan_flow_down} + ${wan_flow_all} + ${lan_rate_down} \
+	     + ${lan_rate_up} + ${wan_rate_down} + ${wan_rate_up} + ${lan_idle} + ${wan_idle} &>/dev/null
+
+	if [ $? -ne 0 ]; then
+                echo "Error: value in group${group} not a figure!" 
+		return 1
+	fi
+
+        json=$(json_create \
+       lan/online/max ${lan_online} \
+       lan/online/idle ${lan_idle} \
+       lan/flow/up/max ${lan_flow_up} \
+       lan/flow/down/max ${lan_flow_down} \
+       lan/flow/all/max ${lan_flow_all} \
+       lan/rate/up/max ${lan_rate_up} \
+       lan/rate/up/avg ${lan_rate_up} \
+       lan/rate/down/max ${lan_rate_down} \
+       lan/rate/down/avg ${lan_rate_down} \
+       lan/rate/all/max ${lan_rate_down} \
+       lan/rate/all/avg ${lan_rate_down} \
+        wan/online/max ${wan_online} \
+        wan/online/idle ${wan_idle} \
+        wan/flow/up/max ${wan_flow_up}x \
+        wan/flow/down/max ${wan_flow_down} \
+        wan/flow/all/max ${wan_flow_all} \
+        wan/rate/up/max ${wan_rate_up} \
+        wan/rate/up/avg ${wan_rate_up} \
+        wan/rate/down/max ${wan_rate_down} \
+        wan/rate/down/avg ${wan_rate_down} \
+        wan/rate/all/max ${wan_rate_down} \
+        wan/rate/all/avg ${wan_rate_down})
+
+        json=$(echo ${json} | jq -j -c .)
+        echo "umc auth $mac $group $json"
+        umc auth "${mac}" "${group}" "${json}"
+}
+uauth_ver2() {
+	#userauth 2 mac group 
+
+	local argc=$#
+	local mac=$2
+	local group=$3
+
+	if ((3!=argc)); then
+		return 1
+	fi
+
+	do_umc_command ${mac} ${group}
+}
+
+uauth_ver3() {
+	#userauth 3 mac json
+	return 
+}
+
+uauth_ver1() {
+#userauth 1 mac
+	
+	local mac=$2
+	local argc=$#
+
+	if((2!=argc)); then
+		return 1
+	fi
+
+	local online=`umc show "{\"mac\":\"$mac\"}"`
+
+ 	local tmpmac=`echo $oneline | jq .mac`
+
+	if [[ "\"$mac\"" != "$tmpmac" ]]; then
+		do_umc_command ${mac} 0
+		return 0 
+	fi	
+
+        local reason=`echo $oneline | jq .reason`
+	if [[ "$reason" != "\"flowlimit\"" ]]; then	
+		do_umc_command ${mac} 0
+		return 0 
+   	fi		
+
+	local wan_flow_all=`echo $oneline | jq .limit.wan.flow.now`
+	local wan_rate_down=`echo $oneline | jq .limit.wan.rate.max`
+
+	local group=$(get_group "${wan_flow_all}" "${wan_rate_down}")
+	
+	do_umc_command ${mac} ${group}
+	return 0
+}
+
+main(){
+	local version=$1
+
+	case ${version} in
+		1|2|3)
+		uauth_ver${version} "$@"
+		;;
+	*)
+		return 1
+		;;
+	esac	
+
+}
+main "$@"
